name: redis-ci

on:
  pull_request:
    paths:
      - "src/server/shared/world/**"
      - "src/server/shared/firehose/**"
      - "src/server/shared/chat/**"
      - "src/server/shared/discovery/**"
      - "src/server/shared/distributed_notifier/**"
      - "src/server/shared/election/**"
      - ".github/workflows/redis-ci.yml"

permissions:
  id-token: write # Needed for gcloud auth.
  contents: read

jobs:
  redis-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: gcloud auth
        uses: ./.github/actions/gcloud-auth
      - name: git lfs pull
        uses: ./.github/actions/cached-lfs-pull
      - name: yarn install
        uses: ./.github/actions/cached-yarn-install
      - name: bazel setup
        uses: ./.github/actions/bazel
      - name: Create/activate virtual environment.
        run: python3 -m venv .venv && echo "$(pwd)/.venv/bin" >> $GITHUB_PATH
      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: 7.0.8-alpine
      - run: ./b test -b -p "src/**/{world,firehose,chat,discovery,distributed_notifier,election}/{/test/*.ts,/*.test.ts}"
        env:
          REDIS_TESTS: 1
          REDIS_TESTS_PORT: 6379
